kind: pipeline
name: default

steps:
  - name: dump-build-output
    image: alpine
    environment:
      COMMIT_ID: $${DRONE_COMMIT_LINK} 
    commands:
      - env
      - export
      - echo $${COMMIT_ID} > drone.commit_id
      - ls -la

  - name: transfer-content
    image: drillster/drone-rsync
    when:
      event: [push]
      branch: [master]
    settings:
      hosts:
        from_secret: swarm_host
      key:
        from_secret: swarm_key
      user:
        from_secret: swarm_user
      source: ./*
      target: /tmp/ruan.dev
      recursive: true
      delete: true

  - name: deploy-hugo-to-swarm
    image: appleboy/drone-ssh
    when:
      branch: [master]
      event: [push]
    environment:
      DRONE_COMMIT: $${DRONE_COMMIT}
      DRONE_STAGE_FINISHED: $${DRONE_STAGE_FINISHED}
      APP_DOMAIN:
        from_secret: app_domain
    settings:
      host:
        from_secret: swarm_host
      username:
        from_secret: swarm_user
      key:
        from_secret: swarm_key
      port: 22
      envs: [app_domain, DRONE_COMMIT, DRONE_STAGE_FINISHED, DRONE_REPO_NAME, DRONE_COMMIT_LINK]
      script:
        - echo $${DRONE_COMMIT} > /tmp/ruan.dev/drone.id
        - echo $${DRONE_STAGE_FINISHED} > /tmp/ruan.dev/drone.stage
        - echo $${DRONE_REPO_NAME} > /tmp/ruan.dev/drone.reponame
        - echo $${DRONE_COMMIT_LINK} > /tmp/ruan.dev/drone.commit_link
        - env #> /tmp/ruan.dev/env.sh
        - sed -i "s/MY_APP_DOMAIN/$$APP_DOMAIN/g" /tmp/ruan.dev/deploy.sh
        - bash /tmp/ruan.dev/deploy.sh
