kind: pipeline
name: default

steps:
  - name: transfer-content:
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: swarm_host
      key:
        from_secret: swarm_key
      user:
        from_secret: swarm_user
    source: ./*
    target: /tmp/ruan.dev
    recursive: true
    delete: true
    when:
      branch: [master]
      event: [push]

#  transfer-compose-to-swarm:
#    image: appleboy/drone-scp
#    host:
#      from_secret: swarm_host
#    username:
#      from_secret: swarm_user
#    key:
#      from_secret: swarm_key
#    target: /tmp/ruan.dev/my-weightloss-blog.com
#    source:
#      - docker-compose.yml
#    when:
#      branch: [master]
#      event: [push]

  - name: deploy-hugo-to-swarm:
    image: appleboy/drone-ssh
    environment:
      DOMAIN:
        from_secret: domain
    settings:
      host:
        from_secret: swarm_host
      username:
        from_secret: swarm_user
      key:
        from_secret: swarm_key
      port: 22
    envs: [domain]
    script:
      - bash /tmp/ruan.dev/deploy.sh
    when:
      branch: [master]
      event: [push]
