kind: pipeline
name: default

steps:
  - name: transfer-content
    image: drillster/drone-rsync
    when:
      event: [push]
      branch: [master]
    settings:
      hosts:
        from_secret: swarm_host
      key:
        from_secret: swarm_key
      user:
        from_secret: swarm_user
      source: ./*
      target: /tmp/ruan.dev
      recursive: true
      delete: true

  - name: dump-build-output
    image: alpine
    environment:
      MYCOMMIT: ruan
    commands:
      - env
      - export
      - echo "commit id: $${DRONE_JOB_FINISHED}" > /tmp/ruan.dev/foo.txt

  - name: deploy-hugo-to-swarm
    image: appleboy/drone-ssh
    when:
      branch: [master]
      event: [push]
    environment:
      DRONE_BUILD_LINK: $$DRONE_BUILD_LINK
      DRONE_COMMIT: $$DRONE_COMMIT
      DRONE_COMMIT_LINK: $$DRONE_COMMIT_LINK
      APP_DOMAIN:
        from_secret: app_domain
    settings:
      host:
        from_secret: swarm_host
      username:
        from_secret: swarm_user
      key:
        from_secret: swarm_key
      port: 22
      envs: [app_domain]
      commands:
        - echo "running command"
        - env
      script:
        - env #> /tmp/ruan.dev/env.sh
        - sed -i "s/MY_APP_DOMAIN/$$APP_DOMAIN/g" /tmp/ruan.dev/deploy.sh
        - bash /tmp/ruan.dev/deploy.sh
    
