kind: pipeline
name: default

steps:
  - name: transfer-content
    image: drillster/drone-rsync
    when:
      event: [push]
      branch: [master]
    settings:
      hosts:
        from_secret: swarm_host
      key:
        from_secret: swarm_key
      user:
        from_secret: swarm_user
      source: ./*
      target: /tmp/ruan.dev
      recursive: true
      delete: true

  - name: deploy-hugo-to-swarm
    image: appleboy/drone-ssh
    when:
      branch: [master]
      event: [push]
    environment:
      APP_DOMAIN:
        from_secret: app_domain
    settings:
      host:
        from_secret: swarm_host
      username:
        from_secret: swarm_user
      key:
        from_secret: swarm_key
      port: 22
      envs: [app_domain]
      script:
        - export DRONE_COMMIT_SHA=$$DRONE_COMMIT_SHA
        - sed -i "s/MY_APP_DOMAIN/$$APP_DOMAIN/g" /tmp/ruan.dev/deploy.sh
        - bash /tmp/ruan.dev/deploy.sh
    
